### PR TITLE
onKeyEnterEvent never has data available

### PR DESCRIPTION
**Pull request by CodeReaper**
Found a problem where callbacks are fired after data has been cleared, have applied a fix in the core.js file. Would you take care of this change? I haven't found a guide on contributing and looking at the files present like the one's in dist, I am assuming there is a process, one has to go thru for it to be done right.

### CODE REVIEW

**Comment by pawelczak** [comment]
Thanks for taking interest in fixing this issue :+1: . 

Yes, there is a process for making changes, but it's not described.. So after you've done your changes you should run command ```grunt devel```, which first run module unit tests, than builds plugin and lastly runs integration tests. If all tests are passed you can push changes to repository. To do this process you need to have gruntjs installed. 
Another thing is writing tests, that checks if your change really fixed the problem. Let me know if your are willing to write them, if not I'll do it. Just describe the problem more precisely, so I can understand it better.

**Comment by CodeReaper** [comment]
I doubt much good would come from me trying to write unit tests for this, but I can most certainly give more details on the issue.

I have setup the plugin using the options 'url', 'getValue' and 'list.onChooseEvent'. The url and getValue are unimportant in relation to the issue. The event handler is defined like so:

 list: {
    onChooseEvent: function() {
        var data = $referenceToInputField.getSelectedItemData();
        // at this point data is always -1, when selecting an autocomplete item with the keyboard
        // however selecting the item by clicking it always provides the expected data
    }
}

The choose event is triggered at the same time as both the click event and keydown (for enter key) event, but I noticed that the keydown event triggers its callbacks (the lines moved in the commit) after clearing out the currently selected item.

Do you understand the issue enough or should I perhaps create a fiddle demonstrating the issue?

**Comment by pawelczak** [comment]
It's all clear to me now. Once again thanks for finding and fixing this issue.

**Comment by czak** [comment]
I'm using version `1.3.1` from `npm`. I believe the error is still there. Has this PR made it into `1.3.1`?

**Comment by czak** [comment]
Okay I could have just checked the tags. The answer is no, and I should patiently wait for the next release or use `master`. Thanks :)

**Comment by CodeReaper** [comment]
It also didn't make it into 1.3.2 when I checked here: 
https://github.com/pawelczak/EasyAutocomplete/releases

... but I am sure it will be coming soon :)

**Comment by pawelczak** [comment]
I want to fix some issues before next release. I'll try to make it faster.

**Comment by czak** [comment]
No worries, I'm using `master` and the issue is fixed.
For anyone interested, using a local folder (e.g. a git checkout) as a dependency in `package.json` quite simple, as explained on SO [here](http://stackoverflow.com/a/14387210).

**Comment by pawelczak** [comment]
Thanks for sharing this information :+1: .

**Pull request merged**
