### PR TITLE
Optional 'ajaxData' callback to supply the 'data' argument of the '$.…

### PR DESCRIPTION
**Pull request by azret**
…ajax' call.

### CODE REVIEW

**Comment by pawelczak** [comment]
Can you write tests for callback and phrase escaping? 

Another thing is that there is a parameter that supports $.ajax settings. It's called ajaxSettings and you can set it to specify all $.ajax parameters. So for example instead of using your:
```javascript
ajaxData: "some data"
```
you can use:
```javascript
ajaxSettings: {
    data: "some data"
}

```

**Comment by azret** [comment]
Thanks. We need the ajaxSettings to be callable with the 'phrase' to generate a 'post' response accordingly. The easiest was to pass dynamic data to $.ajax. Great library. Thank you.

**Comment by pawelczak** [comment]
Can you write tests that supports your code? Please let me know, because if not i'll do it.

**Comment by azret** [comment]
Łukasz, we are not very familiar with the code base. Would you please add a test case for this so that we see how it is done.

**Comment by barrychapman** [comment]
was this type of feature ever implemented? iw ould like to be able to send a POST with the phrase

**Pull request closed without merging**
